export type ActionType 
    // WEB SOCKET
    = 'SOCKET_CONNECT'
    | 'SOCKET_PING'
    | 'SOCKET_PONG'
    | 'SOCKET_JOIN_GAME'
    | 'SOCKET_LAUNCH_GAME'
    | 'SOCKET_MOVE_DOWN'
    | 'SOCKET_MOVE_RIGHT'
    | 'SOCKET_MOVE_LEFT'
    | 'SOCKET_ROTATE_RIGHT'
    | 'SOCKET_ROTATE_LEFT'
    | 'SOCKET_GET_GAME_LIST'
    | 'SOCKET_FALL'
    | 'SOCKET_SET_GAME_SPEED'
    // SERVER RESPONSE
    | 'SRV_EMIT_GAME'
    | 'SRV_EMIT_GAME_LIST'
    | 'SRV_EMIT_PLAYER_CHANGES'
    | 'SRV_UPDATE_GAME'
    // GAME MONITOR
    | 'GAME_MONITOR_DISCONNECT_PLAYER'
    | 'GAME_MONITOR_LAUNCH_GAME'
    | 'GAME_MONITOR_ADD_PLAYER'
    | 'GAME_MONITOR_MOVE_DOWN'
    | 'GAME_MONITOR_MOVE_RIGHT'
    | 'GAME_MONITOR_MOVE_LEFT'
    | 'GAME_MONITOR_ROTATE_RIGHT'
    | 'GAME_MONITOR_ROTATE_LEFT'
    | 'GAME_MONITOR_GET_GAME_LIST'
    | 'GAME_MONITOR_CONNECT_PLAYER'
    | 'GAME_MONITOR_FALL'
    | 'GAME_MONITOR_SET_GAME_SPEED'
    // RANDOM
    | 'ALERT_POP'
    | 'SET_REFRESHMENT_RATE'
    | 'SET_GAMEPAD'

export type Action = {
    type: ActionType
    payload?: any
}